화면구현/community/css/community.css
화면구현/community/free/list.html
화면구현/community/free/view.html
화면구현/community/free/write.html
화면구현/community/mytown/list.html
화면구현/community/mytown/view.html
화면구현/community/mytown/write.html
화면구현/community/qna/comment.html
화면구현/community/qna/list.html
화면구현/community/qna/view.html
화면구현/community/qna/write.html

free,qna,mytown - write 완료
qna - comment 완료

2023.03.08 community 화면구현

---

화면구현/symptoms/Search/resultsymptoms.html
화면구현/symptoms/Search/symptoms.html

2023/03/08
- symptoms result 화면 구현중

2023/03/08 symptoms result 화면 구현중

---

화면구현/member/css/member.css
화면구현/member/myPage2.html

myPage 작업중

---

화면구현/symptoms/Search/resultsymptoms.html
화면구현/symptoms/Search/symptoms.html

2023/03/09
- symptoms 일부수정
- symptoms result 화면구현중

2023/03/09 일부수정 및 화면구현중

---

화면구현/community/css/community.css
화면구현/community/free/view.html
화면구현/community/mytown/list.html
화면구현/community/qna/view.html

mytown - list 완료
qna - view 완료
free - view 작업중

2023.03.09 community 화면구현

---

화면구현/member/calendar.html
화면구현/member/myPage2.html
화면구현/member/myPage3 copy.html
화면구현/member/myPage3.html

myPage 화면 구현중 3 copy 그대로 진행하면 됨

 myPage 화면 구현중

---

화면구현/community/css/community.css
화면구현/community/free/view.html
화면구현/community/mytown/list.html
화면구현/community/mytown/view.html
화면구현/community/qna/view.html

free - view 완료
mytown -veiw 완료

2023.03.10 community

---

화면구현/member/css/member.css
화면구현/member/css/myPage.css
화면구현/member/writeReview.html

 2023/03/13 member 완료

---

swiftER/src/main/java/kr/co/swiftER/controller/ERRestController.java
swiftER/src/main/resources/static/css/er.css
swiftER/src/main/resources/templates/er/er.html

2023-03-17

---

swiftER/src/main/java/kr/co/swiftER/controller/ERRestController.java
swiftER/src/main/java/kr/co/swiftER/controller/SymptomsController.java
swiftER/src/main/java/kr/co/swiftER/dao/SymptomsDAO.java
swiftER/src/main/java/kr/co/swiftER/service/SymptomsService.java
swiftER/src/main/resources/templates/symptoms/_header.html
swiftER/src/main/resources/templates/symptoms/symptoms.html

2023/03/17
- symptoms 유효성 검사 구현중
- symptoms 기능구현중

2023/03/17 symptoms 기능구현중

---

swiftER/src/main/java/kr/co/swiftER/controller/MemberController.java
swiftER/src/main/java/kr/co/swiftER/security/CustomAuthenticationFailureHandler.java
swiftER/src/main/java/kr/co/swiftER/security/MyUserDetails.java
swiftER/src/main/java/kr/co/swiftER/security/SecurityConfig.java
swiftER/src/main/java/kr/co/swiftER/security/SecurityUserService.java
swiftER/src/main/resources/static/css/member/member.css
swiftER/src/main/resources/static/js/postcode.js
swiftER/src/main/resources/templates/index.html
swiftER/src/main/resources/templates/member/login.html
swiftER/src/main/resources/templates/member/registerNor.html

login 실패 시 오류메시지는 영어로 출력이라 나중에 시간나면 if쓰던지 incoding 해서 한글로 출력할지 선택
spring security 대부분 설정 완료
registerNor, login 완료

2023/03/17 13:43 spring security, login, login 실패시 오류메시지, 회원가입, 권한설정

---

swiftER/src/main/java/kr/co/swiftER/security/CustomAuthenticationFailureHandler.java

CustomAuthenticationFailureHandler 내용수정

---

swiftER/src/main/java/kr/co/swiftER/controller/MemberController.java
swiftER/src/main/java/kr/co/swiftER/dao/MemberDAO.java
swiftER/src/main/java/kr/co/swiftER/security/SecurityConfig.java
swiftER/src/main/java/kr/co/swiftER/service/MemberService.java
swiftER/src/main/java/kr/co/swiftER/vo/ERReviewVO.java
swiftER/src/main/resources/mappers/member.xml
swiftER/src/main/resources/static/js/validation.js
swiftER/src/main/resources/templates/member/changePw.html
swiftER/src/main/resources/templates/member/login.html
swiftER/src/main/resources/templates/member/myPage.html
swiftER/src/main/resources/templates/member/registerNor.html

비밀번호 찾기, 마이페이지, 진행중
ERReviewVO 수정

비밀번호 찾기, 마이페이지, 진행중

---

swiftER/src/main/java/kr/co/swiftER/controller/ERRestController.java
swiftER/src/main/java/kr/co/swiftER/controller/SymptomsController.java
swiftER/src/main/resources/templates/symptoms/resultsymptoms.html
swiftER/src/main/resources/templates/symptoms/symptoms.html

2023/03/22
- jquery 체크박스 배열 데이터 전송
- controller 데이터값 받고 post 전송
- 일부 수정

2023/03/22 jquery 기능구현/배열 넘기기

---

swiftER/src/main/java/kr/co/swiftER/controller/CommunityController.java
swiftER/src/main/java/kr/co/swiftER/dao/CommunityDAO.java
swiftER/src/main/java/kr/co/swiftER/service/CommunityService.java
swiftER/src/main/java/kr/co/swiftER/vo/CommunityArticleVO.java
swiftER/src/main/resources/mappers/community.xml
swiftER/src/main/resources/templates/community/freeList.html
swiftER/src/main/resources/templates/community/freeView.html
swiftER/src/main/resources/templates/community/freeWrite.html
swiftER/src/main/resources/templates/community/mytownWrite.html
swiftER/src/main/resources/templates/community/qnaComment.html
swiftER/src/main/resources/templates/community/qnaView.html
swiftER/src/main/resources/templates/index.html

2023.03.22 community view 작업중

---

swiftER/src/main/resources/mappers/member.xml
swiftER/src/main/resources/static/js/validation_doc.js
swiftER/src/main/resources/templates/member/registerDoc.html
swiftER/src/main/resources/templates/member/registerNor.html

의사회원가입 진행중

---

swiftER/src/main/resources/static/js/er.js

2023-03-23 er 페이지 1차 기능 구현 완료

---

swiftER/build.gradle
swiftER/src/main/java/kr/co/swiftER/controller/ERRestController.java
swiftER/src/main/java/kr/co/swiftER/controller/KakaoController.java
swiftER/src/main/java/kr/co/swiftER/controller/MemberController.java
swiftER/src/main/java/kr/co/swiftER/service/KakaoService.java
swiftER/src/main/java/kr/co/swiftER/service/MemberService.java
swiftER/src/main/resources/templates/member/articleList.html
swiftER/src/main/resources/templates/member/changePw.html
swiftER/src/main/resources/templates/member/deleteMember.html
swiftER/src/main/resources/templates/member/findId.html
swiftER/src/main/resources/templates/member/findPw.html
swiftER/src/main/resources/templates/member/login.html
swiftER/src/main/resources/templates/member/myPage.html
swiftER/src/main/resources/templates/member/registerDoc.html
swiftER/src/main/resources/templates/member/registerNor.html
swiftER/src/main/resources/templates/member/reviewList.html
swiftER/src/main/resources/templates/member/terms.html
swiftER/src/main/resources/templates/member/writeReview.html

카카오 api 로그인 포기(주석)
다른거 다하고 해야할듯

카카오 api 로그인 포기(주석)

---

swiftER/src/main/resources/static/css/symptoms.css
swiftER/src/main/resources/templates/symptoms/resultsymptoms.html
swiftER/src/main/resources/templates/symptoms/symptoms.html

2023/03/27
- 결과페이지 화면 일부 수정
- jquery 전송 받아올때 일부 문제 수정중

2023/03/27 result 결과 페이지 구현중

---

swiftER/src/main/java/kr/co/swiftER/controller/ERRestController.java
swiftER/src/main/java/kr/co/swiftER/dao/ERDAO.java
swiftER/src/main/java/kr/co/swiftER/service/ERService.java
swiftER/src/main/java/kr/co/swiftER/vo/ERCateVO.java
swiftER/src/main/java/kr/co/swiftER/vo/ERSubcateVO.java
swiftER/src/main/resources/mappers/er.xml
swiftER/src/main/resources/static/css/common.css
swiftER/src/main/resources/static/js/er.js
swiftER/src/main/resources/static/js/erDetail.js
swiftER/src/main/resources/templates/er/erDetail.html

2023-03-27 리뷰 기능 구현중

---

swiftER/src/main/java/kr/co/swiftER/controller/MemberController.java
swiftER/src/main/java/kr/co/swiftER/dao/MemberDAO.java
swiftER/src/main/java/kr/co/swiftER/service/MemberService.java
swiftER/src/main/resources/mappers/member.xml
swiftER/src/main/resources/static/js/change_doc.js
swiftER/src/main/resources/static/js/change_nor.js
swiftER/src/main/resources/templates/member/changeDoc.html
swiftER/src/main/resources/templates/member/changeNor.html
swiftER/src/main/resources/templates/member/changePw.html
swiftER/src/main/resources/templates/member/deleteMember.html
swiftER/src/main/resources/templates/member/findId.html
swiftER/src/main/resources/templates/member/findIdResult.html
swiftER/src/main/resources/templates/member/findPw.html
swiftER/src/main/resources/templates/member/myPage.html
swiftER/src/main/resources/templates/member/registerDoc.html
swiftER/src/main/resources/templates/member/reviewList.html

2023/03/27 13:42 member

---

swiftER/src/main/java/kr/co/swiftER/controller/MemberController.java
swiftER/src/main/resources/mappers/member.xml

1차 완료
2차 : 달력, 의사 인증 이미지 업로드, sns 로그인

member 1차 완료

---

swiftER/src/main/java/kr/co/swiftER/controller/ERController.java
swiftER/src/main/java/kr/co/swiftER/controller/ERRestController.java
swiftER/src/main/java/kr/co/swiftER/dao/ERDAO.java
swiftER/src/main/java/kr/co/swiftER/service/ERService.java
swiftER/src/main/java/kr/co/swiftER/vo/ERReviewVO.java
swiftER/src/main/resources/mappers/er.xml
swiftER/src/main/resources/static/js/erDetail.js
swiftER/src/main/resources/static/js/popup.js
swiftER/src/main/resources/templates/_header.html
swiftER/src/main/resources/templates/er/er.html
swiftER/src/main/resources/templates/er/erDetail.html

2023-03-28 '리뷰 기능 진행중'

---

swiftER/src/main/java/kr/co/swiftER/controller/SymptomsController.java
swiftER/src/main/java/kr/co/swiftER/dao/SymptomsDAO.java
swiftER/src/main/java/kr/co/swiftER/service/SymptomsService.java
swiftER/src/main/java/kr/co/swiftER/vo/SymptomsSymptomsVO.java
swiftER/src/main/resources/mappers/symptoms.xml
swiftER/src/main/resources/static/css/symptoms.css
swiftER/src/main/resources/templates/symptoms/resultsymptoms.html
swiftER/src/main/resources/templates/symptoms/symptoms.html

2023/03/28
- result 화면 기능구현 완료

2023/03/28 result 기능 구현 완료

---

swiftER/src/main/resources/static/js/symptoms.js
swiftER/src/main/resources/templates/symptoms/_header.html
swiftER/src/main/resources/templates/symptoms/resultsymptoms.html
swiftER/src/main/resources/templates/symptoms/symptoms.html

2023/03/29
- 체크박스 유효성 검사 수정 완료
- 폼 레이아웃 일부 수정 완료

2023/03/29 체크박스 유효성 검사 및 일부 수정

---

swiftER/src/main/java/kr/co/swiftER/controller/ERController.java
swiftER/src/main/java/kr/co/swiftER/controller/ERRestController.java
swiftER/src/main/java/kr/co/swiftER/dao/ERDAO.java
swiftER/src/main/java/kr/co/swiftER/service/ERService.java
swiftER/src/main/resources/mappers/er.xml
swiftER/src/main/resources/static/css/common.css
swiftER/src/main/resources/static/css/er.css
swiftER/src/main/resources/static/js/erDetail.js
swiftER/src/main/resources/static/js/popup.js
swiftER/src/main/resources/templates/er/erDetail.html

2023-03-29 1차 기능구현 완료

---

swiftER/src/main/java/kr/co/swiftER/service/ERService.java

0331 오류 수정

---

swiftER/src/main/resources/static/css/symptoms.css
swiftER/src/main/resources/templates/symptoms/symptoms.html

2023/04/03 css 추가 및 수정

---

swiftER/src/main/java/kr/co/swiftER/controller/MemberController.java
swiftER/src/main/resources/mappers/member.xml
swiftER/src/main/resources/static/css/member/register.css
swiftER/src/main/resources/static/js/validation_nor.js
swiftER/src/main/resources/templates/member/myPage.html
swiftER/src/main/resources/templates/member/registerNor.html

register 부분 form 태그 안에 넣으면서 변경사항 적용중
validation.js 해야함

register 수정중

---

swiftER/src/main/resources/static/js/symptoms.js
swiftER/src/main/resources/templates/symptoms/symptoms.html

2023/04/05
- symptom 개별 데이터 전송시작

2023/04/05 symptom 개별 데이터 전송시작

---

swiftER/src/main/resources/static/css/symptoms.css
swiftER/src/main/resources/templates/symptoms/symptoms.html

2023/04/06
- symptoms 개별 데이터 전송 구현완료
- 이미지 클릭시 해당 div 영역 포커싱 구현중

2023/04/06 symptoms 개별 데이터전송 구현완료

---

swiftER/src/main/java/kr/co/swiftER/controller/MemberController.java
swiftER/src/main/java/kr/co/swiftER/entity/MemberEntity.java
swiftER/src/main/java/kr/co/swiftER/repo/MemberRepo.java
swiftER/src/main/java/kr/co/swiftER/security/SecurityConfig.java
swiftER/src/main/java/kr/co/swiftER/service/MemberService.java
swiftER/src/main/java/kr/co/swiftER/vo/MemberDoctorVO.java
swiftER/src/main/java/kr/co/swiftER/vo/MemberVO.java
swiftER/src/main/resources/static/js/validation_nor.js
swiftER/src/main/resources/templates/member/registerDoc.html
swiftER/src/main/resources/templates/member/registerNor.html

2023/04/06 13:45 register 수정중(일반회원 완료)
- 파일 업로드 확인하고 테스트 해보기
- js 파일 수정해야함

2023/04/06 13:45 register 수정중(일반회원 완료)

---

swiftER/src/main/java/kr/co/swiftER/controller/MemberController.java
swiftER/src/main/java/kr/co/swiftER/vo/MemberDoctorVO.java

multipart 수정

---

swiftER/src/main/java/kr/co/swiftER/controller/SymptomsController.java
swiftER/src/main/java/kr/co/swiftER/dao/SymptomsDAO.java
swiftER/src/main/java/kr/co/swiftER/service/SymptomsService.java
swiftER/src/main/resources/static/js/symptoms.js
swiftER/src/main/resources/templates/symptoms/resultsymptoms.html
swiftER/src/main/resources/templates/symptoms/symptoms.html

2023/04/07
- symptom 데이터 전송중 배열값 전부다 받아오는 과정 수정중

2023/04/07 symptom 데이터 전송 수정중

---

swiftER/src/main/java/kr/co/swiftER/controller/SymptomsController.java
swiftER/src/main/java/kr/co/swiftER/dao/SymptomsDAO.java
swiftER/src/main/java/kr/co/swiftER/service/SymptomsService.java
swiftER/src/main/resources/mappers/symptoms.xml
swiftER/src/main/resources/static/js/symptoms.js

2023/04/10 symptom 2차개발 구상 및 기능 구현중

---

swiftER/src/main/java/kr/co/swiftER/controller/SymptomsController.java
swiftER/src/main/resources/static/css/symptoms.css
swiftER/src/main/resources/static/js/symptoms.js
swiftER/src/main/resources/templates/symptoms/_footer.html
swiftER/src/main/resources/templates/symptoms/symptoms.html

2023/04/11 symptom 화면 구성중

---

swiftER/src/main/java/kr/co/swiftER/controller/MemberController.java
swiftER/src/main/java/kr/co/swiftER/dao/MemberDAO.java
swiftER/src/main/java/kr/co/swiftER/service/MemberService.java
swiftER/src/main/resources/mappers/member.xml
swiftER/src/main/resources/static/css/member/myPage.css
swiftER/src/main/resources/templates/member/myPage.html

2023/04/14 마이페이지 수정중 redirect 하는법 찾기

2023/04/14 마이페이지 수정중

---

swiftER/src/main/java/kr/co/swiftER/controller/MemberController.java
swiftER/src/main/resources/templates/member/myPage.html

2023/04/20 마이페이지 이력 db 넣기

---

swiftER/src/main/java/kr/co/swiftER/controller/ERRestController.java
swiftER/src/main/resources/static/css/er.css
swiftER/src/main/resources/templates/er/er.html
swiftER/src/main/resources/templates/er/erDetail.html

2023-05-02 er 페이지 수정

---

swiftER/build.gradle
swiftER/src/main/java/kr/co/swiftER/controller/MemberController.java
swiftER/src/main/java/kr/co/swiftER/dao/MemberDAO.java
swiftER/src/main/java/kr/co/swiftER/service/MemberService.java
swiftER/src/main/resources/mappers/member.xml
swiftER/src/main/resources/static/css/member/member.css
swiftER/src/main/resources/static/js/registerNor.js
swiftER/src/main/resources/templates/member/articleList.html
swiftER/src/main/resources/templates/member/reviewList.html

2023/05/02 이메일 전송 부분 수정중
자바스크립트로 전송완료되면 바뀌는거 확인해야함

2023/05/02 이메일 전송 부분 수정중

---

swiftER/src/main/resources/static/css/symptoms.css
swiftER/src/main/resources/static/js/symptoms.js
swiftER/src/main/resources/templates/symptoms/symptoms.html

2023/05/12
- 유효성 검사 일부 수정
-  css 수정

2023/05/12 유효성 검사 일부 수정 및 css 수정

---

swiftER/src/main/java/kr/co/swiftER/controller/EmailController.java
swiftER/src/main/java/kr/co/swiftER/controller/MemberController.java
swiftER/src/main/resources/static/js/registerNor.js
swiftER/src/main/resources/static/js/validation_doc.js

member 간단한 수정

---

swiftER/src/main/java/kr/co/swiftER/controller/ERRestController.java
swiftER/src/main/java/kr/co/swiftER/controller/PharmacyController.java
swiftER/src/main/java/kr/co/swiftER/security/SecurityConfig.java
swiftER/src/main/resources/static/css/er.css
swiftER/src/main/resources/static/js/pharmacy.js
swiftER/src/main/resources/templates/_header.html
swiftER/src/main/resources/templates/pharmacy/pharmacy.html

2023-05-16 약국 검색
